FROM gcc:latest

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    time \
    coreutils \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /workspace

RUN chmod 755 /workspace

CMD ["/bin/bash"]